dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    secure: kyX9wtZ8NpbwcdzCY1DFhZuKsZ1wLjebFZlmUaOEbTxron0LD18LSiBZionBGJrBKD8FuCpmy2wvvrIsEuB80cUFRl2CC0a8Onp+lfxdIDRy/ipsx9bMIpIUWFRR5yWX1IchigUOYDjnk55EU5cuEte7LhDY8jueVXTyjUZD96x/6TWL+DCtUVJdudJ7sS0vICZMKgxfxdyNg0mHhMHVBMJ6ndWNqfW4eZlv6jd06IZOou4FsrhYeCzvqt7nXanotePUFiIhGAPJ7bOI745P95GhMKt9ashrwUETcxtRkUjRJkqjXsnDIxwlAboQsEv+jp4gBhwKglNA8Qr1SMcE8ZVSGTCl4Q8dV1oiJmhKOG78kj6TGnw4FdIfVL9uqQLK4eukY29C0p5NJpIUXfn5qGS7T0omsDc3Sth+vjoLHQzVacC0GCgD0b+ZMj0sg7tAyRHSHvolxt4uQiIifd24ytP3X4mmzMotj2a5dlDPITTBJ0Pt/flu8/emJc0NHjlrFbOd7xdziED47JZegt8thnosVHzk+9zmAd+eWAhZUpO1/aPne3IoJpcbnmxc4EFTyhE/weG8ciTJ4jUkp/2Pwv9cq8Si18iwr8dk9lCaY7fsZFde2Sfi5wHhlQbtbCQWkFf+RjivcE6miFrEbEgkC9LMPHyejWy5Zeg5P0guxx4=
