dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    secure: 5ELp2nanlivu2GyUPQA/OgVDK/D8rejjxCCQQICNn7JWFZnzVECNiCL4G2BQyJ0wu0y1Qehjz1nhO/cUwtLcLNoDJ3hNCLewi0qCakFvKHbDd2eejujhqkpTsbY3dXHnX6J5Vcvv0fojl+M/Tkoc198fo1t4R7bkCAyME7n5SMVVhD7PLjSb2vXmjqHHsN+VpdptDKZb7/22BHSXgm1jXdXkUSieMGOLiHeRY72SXn+PAxLbIY7Eqn/IDkWnimT2rkBvfY1G3pdhkQNsc38/fVTRkesly+Ue8PdHiXu/TtKotaUeMi1djirhIQ9kHOiwq1P819TGdTROeqgizRLjACnGeUjkRNTs++4nDmGuTzc9xXDP+zY/ENiSnv2uUrXq+IyaVID3ajMRrFJwmEvLNOau3ZOLNhwH8UpJv/OrScOuk3QQLfqB8w3rLky0lEXmzSfBZf0Ppv/I6TcjWl1+drWJrw61fDkyFl2EhLti1Gdp1mGHq+l4BCGpZYQu6AITgXl9MpHbRK7JWXyCC5Y2S/lDM9wxlS+ScufcohvEppQLsqVUB4gKI6yzPIVVRMsBwF89g+Mlx5bOo3ypSnsLDNxHJPHqncempb10ama38InGGKoOvRmAmyf2ldMa/NtCvfRNQQdBD+h7MFxomedcQWjjq2VsWOLt1aqGYdgiYA0=
