dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    secure: Rg7GtrU0uyOHR8ahuRBBia/UrOHN7/xc3ZaF+QOBA9XhGlvwSkUCjBIi6Z6oS6WkaRfwd8sYZYYYppGftElptVtufma5m/o7eqziDtBibZHdHc7gTidR6h/7yRTpoqPtXg2H7FB6T459RhCAgYGWmOMA2DF3paqoJAggfThXoCeNUaz7CFDiQpgTO6WFH3O++W2m/LIEImr/QH3Tim1zrWMIHJz6pLgiUs92rfNZhciFZ9DKqlu5QtclTZlEGqiyXKBaByKqWserjWmkBnVtTtXGHcUIeGUPQjL7ul9hMsaDbrg8+W9/DPaiqiLQmRw6Nke+5Df5iyyRQeyNVPiVgl/1K/RMyQxT6H67TWDACUtKGESFpfvIR5XT9XQbH4RPD3VoW9zR5+mqSw9pd2qX2Mkf1SZqX998VSY34i8VmBUDYZCA/EbH7z1GYhl2qbzLrXGGkgkXC3WAB6vBmHxowocNzxUfsjOvUCk173RkXQXp0L1K8WLlCIpPxT81rivi0S/tikgOgLQdMEfRdfpON8gIc9eSBjhAx6zB7nHNdBLVSvxKXNZ+jDG1u+Du2jmbuJvvHmwrpMMJw8grIJ5CQqvRW3BKPmWOOh2/Bzb5UR4IhUZ0kY62pjTRDFaLSs0F0BIt6I1QFABVcASlUbnzSihxltc65itbpWGe1PFHf0s=
