---
- name: install ruby dependencies
  hosts: all
  become: true
  tasks:
   - name: install ruby deps
     apt:
       name: "{{ item }}"
       state: present
     loop:
       - ruby-full
       - ruby-bundler
       - build-essential
